### ISSUE TITLE
Use pool library instead of epgsql_pool or emysql

### ISSUE THREAD

**Issue by manuel-rubio** [dbi-beam/dbi#12]
Instead of use specific pools for each driver, the idea is use poolboy or wpool instead to use only one pool library for all of the SQL possibilities.

**Comment by manuel-rubio** [comment]
@tsloughter I could suggest to create a dbi_pgo project if you want. My idea is provide different providers to the coders can choose but keeping dbi as core base.

**Comment by manuel-rubio** [comment]
In https://github.com/dbi-beam/dbi_pgsql and https://github.com/dbi-beam/dbi_mysql is implemented poolboy as pool for connections so, it's done.

**Comment by tsloughter** [comment]
Ah ok, didn't realize it was already done.

**Comment by manuel-rubio** [comment]
@tsloughter I did it today :-P
